### ISSUE TITLE
How to have the Dart compiler tree-shake/strip my logging strings in release mode?

### ISSUE THREAD

**Issue by andynewman10** [dart-lang/language#4070]
I currently have a class centralizing all the logging in my application:

```
class Logger {
  static void log(String logString) {
    print(logString);
  }
}
```
To make sure I don't log anything in release mode, I can easily write the following code:

```
  static void log(String msg) {
    const bool kReleaseMode = bool.fromEnvironment('dart.vm.product');
    if (!kReleaseMode) {
      print(msg);
    }
  }
```
However, when the following code:

```
Logger.log("Hello, World");
```
is compiled using
```
dart run build_runner build -r
```
my "Hello, World" log string DOES appear in the final compiled file. I don't want this. I want all log strings to disappear in release mode.

I would have expected the Dart compiler to detect that `!ReleaseMode` is always false, and somehow "tree-shake" away all unneeded code, including the instanciation of the (constant) string `"Hello, World"`.

How can I automatically strip all constant strings passed to Logger.log in release mode?

I looked for different ways, eg. debug/release conditional imports, but in the end I couldn't find a way to accomplish this.

**Comment by rrousselGit** [comment]
Running your program through `build_runner` is different,. I'm not certain `build_runner` runs builders in "release mode".

**Comment by andynewman10** [comment]
@rrousselGit The `-r` in `dart run build_runner build -r` stands for release mode.

Is there another build method that I can use to strip the strings?

**Comment by rrousselGit** [comment]
`-r` is about which options get picked up in the `build.yaml` of your generators/projects.
I don't think this influences how builders are compiled

**Comment by rrousselGit** [comment]
You can try using `log` from package:build

Logs could then be controlled with `build_runner build --verbose`, where the flag controls whether or not a log appears.

**Comment by andynewman10** [comment]
Isn't package:build a dev_dependencies-only package?

I tried to do it as you suggested, but I declared package:build in the dependencies section.

pubspec.yaml:
```
dependencies:
  build: ^2.4.1 # required in the 'dependencies' section, not 'dev_dependencies', since I want to use log.info from my application code, not from a Builder's code

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
```
build.yaml:
```
targets:
  $default:
    builders:
      build_web_compilers:entrypoint:
        generate_for:
          - web/**.dart
        options:
          compiler: dart2js
```
myfile.lib:
```
import 'package:build/build.dart';

void main() {
  log.info("TEST");
  [...]
```
Build command:
```
dart run build_runner build
```
This does not build.
```
Skipping compiling com_example_application|web/myfile.dart with dart2js because some of its
transitive libraries have sdk dependencies that are not supported on this platform:
[...]
```
Maybe I misunderstood your proposed approach.

**Comment by ykmnkmi** [comment]
You can use environment variables, `logger.dart`:
```dart
abstract interface class Logger {
  static void log(String logString) {
    if (const bool.fromEnvironment('enable_logging')) { // defaults to false
      console.log(logString.toJS);
    }
  }
}
```
`build.yaml`:
```yaml
global_options:
  build_web_compilers:ddc: # dev. web compiler
    options:
      environment:
        enable_logging: true
```
