### ISSUE TITLE
Language features for FFI

### ISSUE THREAD

**Issue by sjindel-google** [dart-lang/language#411]
This is a meta-issue for the language features which would simplify the FFI API.

/cc @dcharkes @mkustermann @mraleph @leafpetersen @lrhn 

# Type-level functions

The FFI has as set of types which correspond to C types: `Int8`, `Int64`, `Double`, `Float`, `Pointer`, etc. Each of these types has a related Dart type, e.g. `int`, `double` or `Pointer`.
These types cannot be instantiated in Dart (exception as annotations), but are used as type variables and in function signatures to specify additional behavior. For example, the `Pointer` class has two methods `load` and `store`:

```Dart
class Pointer<T extends NativeType> {
  U load<U>();
  store(Object value)
}
```

Unfortunately, this API can't enforce the relationship between the `NativeType`s and corresponding `Dart` types (this is done via a custom pass in the front-end). So the following illegal code will type-check:

```Dart
Pointer<Int64> x = ...;
x.load<String>();
```

# Access to function return type

Enforcing the correspondence between these two sets of types is further complicated by the use of function types to represent native function signatures. The following API method creates a native function address which calls a Dart method:

```Dart
external Pointer<NativeFunction<T>> fromFunction<T extends Function>(
    Function f, {dynamic exceptionalReturn: 0});
```

Here, we want to enforce that the type of `exceptionalReturn` corresponds to the return type of `f`, and that all the types mentioned in the signature of `f` correspond piece-wise to the native types mentioned in the function type `T`.

The same holds for `asFunction`, although it's slightly simpler.

@dcharkes Are there others?

**Comment by dcharkes** [comment]
For reference, all the error messages we throw in our VM transformer:

```yaml
FfiTypeMismatch:
  # Used by dart:ffi
  template: "Expected type '#type' to be '#type2', which is the Dart type corresponding to '#type3'."
  external: test/ffi_test.dart

FfiTypeInvalid:
  # Used by dart:ffi
  template: "Expected type '#type' to be a valid and instantiated subtype of 'NativeType'."
  external: test/ffi_test.dart

FfiTypeUnsized:
  # Used by dart:ffi
  template: "Method '#name' cannot be called on something of type '#type' as this type is unsized."
  external: test/ffi_test.dart

FfiFieldAnnotation:
  # Used by dart:ffi
  template: "Field '#name' requires exactly one annotation to declare its C++ type, which cannot be Void. dart:ffi Structs cannot have regular Dart fields."
  external: test/ffi_test.dart

FfiNotStatic:
  # Used by dart:ffi
  template: "#name expects a static function as parameter. dart:ffi only supports calling static Dart functions from c."
  external: test/ffi_test.dart

FfiFieldInitializer:
  # Used by dart:ffi
  template: "Field '#name' is a dart:ffi Pointer to a struct field and therefore cannot be initialized before constructor execution."
  external: test/ffi_test.dart

FfiExtendsSealedClass:
  # Used by dart:ffi
  template: "Class '#name' cannot be extended."
  external: test/ffi_test.dart

FfiStructGeneric:
  # Used by dart:ffi
  template: "Struct '#name' should not be generic."
  external: test/ffi_test.dart

FfiWrongStructInheritance:
  # Used by dart:ffi
  template: "Struct '#name' must inherit from 'Struct<#name>'."
  external: test/ffi_test.dart
```

For every one of these being able to express them in the type system would remove a ffi-specific check.
