### ISSUE TITLE
Incorrect indentation in pubspec.yaml does not result in error during pub get

### ISSUE THREAD

**Issue by Jannik-dev** [dart-lang/language#4173]
Hi,

I recently discovered that `pub get` worked fine when the version constraint on a hosted package has a wrong indentation.

# Issue

This is my example (version is indented too much), it essentially acts like no version is specified, which could be quite tricky to resolve in the future:
```
dependencies:
  plugin_platform_interface:
    hosted:
      url: https://pub.dev
      version: 2.1.3
```

When using the [pubspec_parse](https://pub.dev/packages/pubspec_parse) (version `1.3.0`) an error is thrown which I would expect from `pub get` as well.

# Additional Info
dart version is `3.5.4`
