### ISSUE TITLE
No return statement should be compile time error.

### ISSUE THREAD

**Issue by safield** [dart-lang/language#834]
In dart, I can write a method that returns type Foo. I can then omit the return statement from the method, not returning any instance of Foo.

This should be a compile time error.

**Comment by leisim** [comment]
You can already do that using an `analysis_options.yaml` file.

```yaml
analyzer:
  errors:
    always_declare_return_types: error
```

But I agree, it should be the default behavior.
